apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: backend-tests-go-xetwvdsn
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/backend-tests-go-xetwvdsn:7bdf5e10b537ed3a618d5aa135eac4adfc02c4ff@sha256:4860098e4ee499198addccc73c726270829e3eb998fc51b4616f53d3fa323a63
          name: container-image
